@startuml

[*] --> モータ駆動準備中
モータ駆動準備中 --> モータ駆動準備中 : アクセル開度 > 0

モータ駆動準備中 --> モータ駆動停止中 : アクセル開度 == 0

モータ駆動停止中 --> モータ駆動中 :  アクセル開度 >= xxx

モータ駆動中 --> モータ駆動停止中 :  アクセル開度 <= yyy

モータ駆動中 --> アクセル開度再設定 :  2ms経過
アクセル開度再設定 --> モータ駆動中

@enduml